INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id) VALUES (1, 'Bank', 'Bank', null, null, null, 'bank', null, 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null);
INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id) VALUES (2, 'Primary', 'Primary', null, null, null, 'primary', null, 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null);
INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id) VALUES (3, 'Secondary', 'Secondary', null, null, null, 'secondary', null, 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null);
INSERT INTO maven.organization_external_id (idp,external_id,organization_id)
	VALUES ('OPTUM','foobar',2);
INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id) VALUES (4, 'With_Activated', 'With_Activated', null, null, null, 'with_activated', '2023-05-12', 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null);
 INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, terminated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id) VALUES (5, 'With_Terminated', 'With_Terminated', null, null, null, 'with_activated', '2023-05-12', '2023-05-15', 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null);

# Org affiliations setup for files under .storage/tertiary/
INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id, data_provider) VALUES (6, 'data_provider_org', 'data_provider_org', null, null, null, 'tertiary', null, 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null, 1);
INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id, data_provider) VALUES (7, 'sub_org_a', 'sub_org_a', null, null, null, null, null, 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null, 0);
INSERT INTO maven.organization (id, name, display_name, internal_summary, vertical_group_version, message_price, directory_name, activated_at, medical_plan_only, employee_only, bms_enabled, rx_enabled, icon, json, session_ttl, multitrack_enabled, internal_type, education_only, alegeus_employer_id, data_provider) VALUES (8, 'sub_org_b', 'sub_org_b', null, null, null, null, null, 0, 0, 1, 1, null, '{}', null, 1, 'TEST', 0, null, 0);
INSERT INTO maven.organization_external_id (idp,external_id,organization_id, data_provider_organization_id) VALUES (null,'foo',7,6);
INSERT INTO maven.organization_external_id (idp,external_id,organization_id, data_provider_organization_id) VALUES (null,'bar',8,6);